[workspace]
members = [
    "halo2",
    "halo2_gadgets",
    "halo2_proofs",

    "halo2wrong",
    "ecc",
    "ecdsa",
    "integer",
    "maingate",
    "pos_merkle",
    "halo2curves",
    "web",
    "tree_maker",
    "prf_gen",
    "prfs_backend",
    "bus-mapping",
    "keccak256",
    "gadgets",
    "mock",
    "external-tracer",
    "geth-utils",

    "web_demo",
]
