[package]
name = "web_demo"
version = "0.0.1"
edition = "2021"
license = "MIT OR Apache-2.0"
readme = "../README.md"

[dependencies]
wasm-bindgen = "0.2"

[lib]
crate-type = ["cdylib"]

[dev-dependencies]
rand_core = { version = "0.6", default-features = false }
